// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQpd5joRnMputU3M4xIuwPq2Ri-LfPdZw',
    appId: '1:1035607342772:web:e9744f30407365efb0a1e1',
    messagingSenderId: '1035607342772',
    projectId: 'flutter-d3c3c',
    authDomain: 'flutter-d3c3c.firebaseapp.com',
    storageBucket: 'flutter-d3c3c.firebasestorage.app',
    measurementId: 'G-8TBS7JYDC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW0Ho66DyXiHrmtuoEK2zq53UjPaeJbqk',
    appId: '1:1035607342772:android:ce0fb85ffc461e60b0a1e1',
    messagingSenderId: '1035607342772',
    projectId: 'flutter-d3c3c',
    storageBucket: 'flutter-d3c3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-VxEC9azEfsefZEQJ_g3bjG5oisxCItY',
    appId: '1:1035607342772:ios:fd9a4428dfd35d2ab0a1e1',
    messagingSenderId: '1035607342772',
    projectId: 'flutter-d3c3c',
    storageBucket: 'flutter-d3c3c.firebasestorage.app',
    iosBundleId: 'com.example.netflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-VxEC9azEfsefZEQJ_g3bjG5oisxCItY',
    appId: '1:1035607342772:ios:fd9a4428dfd35d2ab0a1e1',
    messagingSenderId: '1035607342772',
    projectId: 'flutter-d3c3c',
    storageBucket: 'flutter-d3c3c.firebasestorage.app',
    iosBundleId: 'com.example.netflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQpd5joRnMputU3M4xIuwPq2Ri-LfPdZw',
    appId: '1:1035607342772:web:1166569892e7f688b0a1e1',
    messagingSenderId: '1035607342772',
    projectId: 'flutter-d3c3c',
    authDomain: 'flutter-d3c3c.firebaseapp.com',
    storageBucket: 'flutter-d3c3c.firebasestorage.app',
    measurementId: 'G-0LT8NPQRS9',
  );
}
